//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client1Application.HelloWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWebService.HelloWebServiceSoap")]
    public interface HelloWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getmessgae", ReplyAction="*")]
        Client1Application.HelloWebService.GetmessgaeResponse Getmessgae(Client1Application.HelloWebService.GetmessgaeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getmessgae", ReplyAction="*")]
        System.Threading.Tasks.Task<Client1Application.HelloWebService.GetmessgaeResponse> GetmessgaeAsync(Client1Application.HelloWebService.GetmessgaeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetmessgaeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Getmessgae", Namespace="http://tempuri.org/", Order=0)]
        public Client1Application.HelloWebService.GetmessgaeRequestBody Body;
        
        public GetmessgaeRequest() {
        }
        
        public GetmessgaeRequest(Client1Application.HelloWebService.GetmessgaeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetmessgaeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetmessgaeRequestBody() {
        }
        
        public GetmessgaeRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetmessgaeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetmessgaeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client1Application.HelloWebService.GetmessgaeResponseBody Body;
        
        public GetmessgaeResponse() {
        }
        
        public GetmessgaeResponse(Client1Application.HelloWebService.GetmessgaeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetmessgaeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetmessgaeResult;
        
        public GetmessgaeResponseBody() {
        }
        
        public GetmessgaeResponseBody(string GetmessgaeResult) {
            this.GetmessgaeResult = GetmessgaeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebServiceSoapChannel : Client1Application.HelloWebService.HelloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebServiceSoapClient : System.ServiceModel.ClientBase<Client1Application.HelloWebService.HelloWebServiceSoap>, Client1Application.HelloWebService.HelloWebServiceSoap {
        
        public HelloWebServiceSoapClient() {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client1Application.HelloWebService.GetmessgaeResponse Client1Application.HelloWebService.HelloWebServiceSoap.Getmessgae(Client1Application.HelloWebService.GetmessgaeRequest request) {
            return base.Channel.Getmessgae(request);
        }
        
        public string Getmessgae(string name) {
            Client1Application.HelloWebService.GetmessgaeRequest inValue = new Client1Application.HelloWebService.GetmessgaeRequest();
            inValue.Body = new Client1Application.HelloWebService.GetmessgaeRequestBody();
            inValue.Body.name = name;
            Client1Application.HelloWebService.GetmessgaeResponse retVal = ((Client1Application.HelloWebService.HelloWebServiceSoap)(this)).Getmessgae(inValue);
            return retVal.Body.GetmessgaeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client1Application.HelloWebService.GetmessgaeResponse> Client1Application.HelloWebService.HelloWebServiceSoap.GetmessgaeAsync(Client1Application.HelloWebService.GetmessgaeRequest request) {
            return base.Channel.GetmessgaeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client1Application.HelloWebService.GetmessgaeResponse> GetmessgaeAsync(string name) {
            Client1Application.HelloWebService.GetmessgaeRequest inValue = new Client1Application.HelloWebService.GetmessgaeRequest();
            inValue.Body = new Client1Application.HelloWebService.GetmessgaeRequestBody();
            inValue.Body.name = name;
            return ((Client1Application.HelloWebService.HelloWebServiceSoap)(this)).GetmessgaeAsync(inValue);
        }
    }
}
